### PR TITLE
switch to html anchor tags

### PR DESCRIPTION
**Pull request by Woozl**
@scrummish @mbwatson I made an attempt to get this working, but am still running into strange inconsistencies and behavior. The package being used for anchor links, [gatsby-plugin-anchor-links](https://www.npmjs.com/package/gatsby-plugin-anchor-links), adds the scroll functionality with `scrollToElement()`, but doesn't seem to implement any of the routing. I don't think it needs to be overcomplicated that much, I believe we should be able to use the `a` tag here. 

The original bug is fixed, for example, a url with a `#` sets the initial scroll position. Here's some links to try:

[http://localhost:8000/fellows/cohort1/#michelle-daya](http://localhost:8000/fellows/cohort1/#michelle-daya)
[http://localhost:8000/fellows/cohort1/#fayuan-wen](http://localhost:8000/fellows/cohort1/#fayuan-wen)

The odd behavior:
1. When you load the site with an `#`, the scroll position is set at the top of the page, making the bio/image sit behind the header. This issue isn't present when you click one of the links while being on the cohort page, because of the styled `::before` element with some visually hidden spacing. I have no clue why this doesn't work when you first load the page however.
2. Clicking an anchor link at the top of the cohort page has a ~1 second delay before moving when `scroll-behavior: smooth` is enabled. Toggle it on the `html` tag in the devtools to see the difference. Again, no idea, but not a great UX.

Any ideas welcome 😅

### CODE REVIEW

**Comment by mbwatson** [comment]
you are right -- strange! i suspect some conflict with the`a` tag and Gatsby's opinion on routing, which is coordination that plugin was intended to handle of for us :frowning:. that plugin hasn't seen any development in two years--maybe it doesn't play nicely with new Gatsby?

**Comment by Woozl** [comment]
This is the code from `gatsby-plugin-anchor-links` that runs during an `onClick` event on the link:

```js
export function scroller(target, offset = 0, duration = 1000) {
  scrollToElement(target, {
    duration,
    offset,
  });
}

export function handleLinkClick(to, e, onAnchorLinkClick) {
  /**
   * Log warnings on click
   */
  const improperFormatting = !to.includes('/') || !to.includes('#');
  if (improperFormatting) logWarning(errorTypes.IMPROPPER_FORMATTING);

  if (isBrowser && to.includes('#')) {
    const [anchorPath, anchor] = to.split('#');
    if (window.location.pathname === withPrefix(anchorPath)) {
      e.preventDefault();
      scroller(
        `#${anchor}`,
        window.gatsby_scroll_offset,
        window.gatsby_scroll_duration
      );
    }
  }

  if (onAnchorLinkClick) onAnchorLinkClick();
}
```

It is just a cosmetic scroll to the element's id. I can't find any route update stuff unless I'm not seeing it. We could open an issue on the repo but it doesn't seem to be maintained as you said.

I'd rather switch away from this plugin, I actually just saw [this page on the Gatsby docs](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#recommendations-for-programmatic-in-app-navigation) suggesting you use either `a` tags or `navigate()`, I'll give navigate a shot tomorrow.

**Comment by mbwatson** [comment]
:+1: sounds like a plan!

**Comment by Woozl** [comment]
@mbwatson let me know what you think, I added some spacing so the links aren't behind the header

**Review by mbwatson — APPROVED** [review]
this works awesome in chrome. the same behavior on first render happens still, though, in firefox. either way, it is already an improvement, though, and should be merged. 

:+1: good job

**Comment by Woozl** [comment]
@mbwatson ugh, I have no idea why, it should be the default browser behavior now, but maybe I overlooked something. Should I close the issue as well or mark it as broken on firefox still?

**Pull request merged**
